import { CountryItem } from "../types/Types";

export const countryCodes: CountryItem[] = [
    {
        "name": {
            "en": "Albania",
            "da": "Albanien",
            "ru": "Албания",
            "pl": "Albania",
            "ua": "Албанія",
            "cz": "Albánie",
            "by": "Албанія",
            "pt": "Albânia",
            "es": "Albania",
            "ro": "Albania",
            "bg": "Албания",
            "de": "Albanien",
            "fr": "Albanie",
            "nl": "Albanië",
            "it": "Albania",
            "cn": "阿尔巴尼亚",
            "zh": "阿爾巴尼亞",
            "ee": "Albaania",
            "jp": "アルバニア",
            "he": "אלבניה",
            "el": "Αλβανία",
            "ar": "ألبانيا",
            "tr": "Arnavutluk",
            "si": "Albanija"
        },
        "dial_code": "+355",
        "code": "AL",
        "flag": "🇦🇱"
    },
    {
        "name": {
            "en": "Bosnia and Herzegovina",
            "da": "Bosnien og Hercegovina",
            "ru": "Босния и Герцеговина",
            "pl": "Bośnia i Hercegowina",
            "ua": "Боснія і Герцеговина",
            "cz": "Bosna a Hercegovina",
            "by": "Боснія і Герцагавіна",
            "pt": "Bósnia e Herzegovina",
            "es": "Bosnia y Herzegovina",
            "ro": "Bosnia si Hertegovina",
            "bg": "Босна и Херцеговина",
            "de": "Bosnien und Herzegowina",
            "fr": "Bosnie Herzégovine",
            "nl": "Bosnië-Herzegovina",
            "it": "Bosnia Erzegovina",
            "cn": "波斯尼亚和黑塞哥维那（简称：波黑",
            "zh": "波斯尼亞和黑塞哥維那（簡稱：波黑",
            "ee": "Bosnia ja Hertsegoviina",
            "jp": "ボスニア・ヘルツェゴビナ",
            "he": "בוסניה והרצגובינה",
            "el": "Βοσνία και Ερζεγοβίνη",
            "ar": "البوسنة والهرسك",
            "tr": "Bosna Hersek",
            "si": "Bosna in Hercegovina"
        },
        "dial_code": "+387",
        "code": "BA",
        "flag": "🇧🇦"
    },
    {
        "name": {
            "en": "Croatia",
            "da": "Kroatien",
            "ru": "Хорватия",
            "pl": "Chorwacja",
            "ua": "Хорватія",
            "cz": "Chorvatsko",
            "by": "Харватыя",
            "pt": "Croácia",
            "es": "Croacia",
            "ro": "Croaţia",
            "bg": "Хърватия",
            "de": "Kroatien",
            "fr": "Croatie",
            "nl": "Kroatië",
            "it": "Croazia",
            "cn": "克罗地亚",
            "zh": "克羅地亞",
            "ee": "Horvaatia",
            "jp": "クロアチア",
            "he": "קרואטיה",
            "el": "Κροατία",
            "ar": "كرواتيا",
            "tr": "Hırvatistan",
            "si": "Hrvaška"
        },
        "dial_code": "+385",
        "code": "HR",
        "flag": "🇭🇷"
    },
    {
        "name": {
            "en": "Italy",
            "da": "Italien",
            "ru": "Италия",
            "pl": "Włochy",
            "ua": "Італія",
            "cz": "Itálie",
            "by": "Італія",
            "pt": "Itália",
            "es": "Italia",
            "ro": "Italia",
            "bg": "Италия",
            "de": "Italien",
            "fr": "Italie",
            "nl": "Italië",
            "it": "Italia",
            "cn": "意大利",
            "zh": "意大利",
            "ee": "Itaalia",
            "jp": "イタリア",
            "he": "איטליה",
            "el": "Ιταλία",
            "ar": "إيطاليا",
            "tr": "İtalya",
            "si": "Italija"
        },
        "dial_code": "+39",
        "code": "IT",
        "flag": "🇮🇹"
    },
    {
        "name": {
            "en": "Kosovo, Republic of",
            "si": "Kosovo"
        },
        "dial_code": "+383",
        "code": "XK",
        "flag": "🇽🇰"
    },
    {
        "name": {
            "en": "Macedonia, The Former Yugoslav Republic of",
            "da": "Makedonien, Den Tidligere Jugoslaviske Republik",
            "ru": "Македония, Бывшая Югославская Республика",
            "pl": "Macedonia, Była Jugosłowiańska Republika",
            "ua": "Македонія, колишня югославська республіка",
            "cz": "Makedonie, Bývalá jugoslávská republika",
            "by": "Македонія, былая югаслаўская рэспубліка",
            "pt": "Macedónia",
            "es": "Macedonia, Antigua República Yugoslava de",
            "ro": "Macedonia, Fosta Republică Iugoslavă a",
            "bg": "Македония, бившата югославска република",
            "de": "Mazedonien, die ehemalige jugoslawische Republik",
            "fr": "Macédoine, ancienne République yougoslave de",
            "nl": "Macedonië, de voormalige Joegoslavische Republiek",
            "it": "Macedonia, ex Repubblica iugoslava di",
            "cn": "前南斯拉夫共和国马其顿",
            "zh": "前南斯拉夫共和國馬其頓",
            "ee": "Makedoonia, endine Jugoslaavia Makedoonia Vabariik",
            "jp": "マケドニア、旧ユーゴスラビア共和国",
            "he": "מקדוניה",
            "el": "Βόρεια Μακεδονία",
            "ar": "مقدونيا، جمهورية يوغوسلافيا السابقة",
            "tr": "Makedonya, Eski Yugoslav Cumhuriyeti",
            "si": "Severna Makedonija"
        },
        "dial_code": "+389",
        "code": "MK",
        "flag": "🇲🇰"
    },
    {
        "name": {
            "en": "Serbia",
            "da": "Serbien",
            "ru": "Сербия",
            "pl": "Serbia",
            "ua": "Сербія",
            "cz": "Srbsko",
            "by": "Сербія",
            "pt": "Sérvia",
            "es": "Serbia",
            "ro": "Serbia",
            "bg": "Сърбия",
            "de": "Serbien",
            "fr": "Serbie",
            "nl": "Servië",
            "it": "Serbia",
            "cn": "塞尔维亚",
            "zh": "塞爾維亞",
            "ee": "Serbia",
            "jp": "セルビア",
            "he": "סרביה",
            "el": "Σερβία",
            "ar": "صربيا",
            "tr": "Sırbistan",
            "si": "Srbija"
        },
        "dial_code": "+381",
        "code": "RS",
        "flag": "🇷🇸"
    },
    {
        "name": {
            "en": "Slovenia",
            "da": "Slovenien",
            "ru": "Словения",
            "pl": "Słowenia",
            "ua": "Словенія",
            "cz": "Slovinsko",
            "by": "Славенія",
            "pt": "Eslovénia",
            "es": "Eslovenia",
            "ro": "Slovenia",
            "bg": "Словения",
            "de": "Slowenien",
            "fr": "Slovénie",
            "nl": "Slovenië",
            "it": "Slovenia",
            "cn": "斯洛文尼亚",
            "zh": "斯洛文尼亞",
            "ee": "Sloveenia",
            "jp": "スロベニア",
            "he": "סלובניה",
            "el": "Σλοβενία",
            "ar": "سلوفينيا",
            "tr": "Slovenya",
            "si": "Slovenija"
        },
        "dial_code": "+386",
        "code": "SI",
        "flag": "🇸🇮"
    },
];
